archives:
  - files:
      # Ensure only built binary is archived
      - 'none*'
    format: zip
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
before:
  hooks:
    - 'go mod download'
builds:
  - dir: .
    binary: '{{ .Env.PLUGIN }}'
    main: 'cmd/{{ .Env.PLUGIN }}/main.go'
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath

    # build for everything Vault supports
    goos:
      - darwin
      - freebsd
      - linux
      - netbsd
      - openbsd
      - solaris
      - windows
    goarch:
      - '386'
      - amd64
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: '386'
      - goos: darwin
        goarch: arm
      - goos: freebsd
        goarch: arm64
      - goos: netbsd
        goarch: arm64
      - goos: openbsd
        goarch: arm64
      - goos: solaris
        goarch: '386'
      - goos: solaris
        goarch: arm
      - goos: solaris
        goarch: arm64
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w -X main.Version={{ .Env.PLUGIN_VERSION }}
    mod_timestamp: '{{ .CommitTimestamp }}'

checksum:
  algorithm: sha256
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'

snapshot:
  name_template: "{{ .Tag }}-next"

release:
  ids:
    - none
  disable: true